config/routes.rb
Equip::Application.routes.draw do

  resources :tags

  resources :settings

  resources :events

  get '/logout', to: "bookings#logout"
  get '/invaliduser', to: "pages#invaliduser"
  get '/users/:column.json', to: "users#column", defaults: {format: :json}, constraints: lambda{|request|User.column_names.include?(request.params[:column])}
  get '/equipment/bytag/:tag_id', to: "equipment#tags", as: 'bytag'
  get '/equipment/:column.json', to: "equipment#column", defaults: {format: :json}, constraints: lambda{|request|Equipment.column_names.include?(request.params[:column])}

  get '/bookings/daterange', to: "bookings#daterange", defaults: {format: :json}

  resources :categories
  resources :equipment
  resources :users
  resources :bookings

  root :to => 'pages#home'

end

app/views/shared/_header.html.erb
<div class="header row">
	<div class="large-6 small-12 columns">
		<h1>MAD Equipment</h1>
	</div>
</div>

app/views/shared/_legend.html.erb
<div id="legend">
	<div class="small-3 columns" style="background:#9933cc">Upcoming</div>
	<div class="small-3 columns" style="background:#3366ff">Active</div>
	<div class="small-3 columns" style="background:#00aa22">Finished</div>
	<div class="small-3 columns" style="background:#dd0000">Overdue</div>
</div>

app/views/shared/_navigation.html.erb
<nav class="top-bar">
	<ul class="left title-area">
		<% Setting.find_by_key("site_name").nil? ? site_name = "Booking System" : site_name = Setting.find_by_key("site_name").value %>
    	<li class="name"><h1><%= link_to site_name, root_path %></h1></li>
		<li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  	</ul>
	<section class="top-bar-section">
		<ul>
			<li class="divider"></li>
			<li><%= link_to 'Users', users_path %></li>
			<li><%= link_to 'Equipment', equipment_index_path %></li>
			<li><%= link_to 'Bookings', bookings_path %></li>
			<li class="divider"></li>
		</ul>
		<ul class="right">
			<li class="divider"></li>
			<li><%= link_to 'Settings', settings_path %></li>
			<% logout_path = root_path + 'logout' %>
			<li><%= link_to 'Logout ' + session[:cas_user], logout_path %></li>

		<ul>
	</section>
</nav>

app/views/shared/_search_form.erb
<div class="search row collapse">
	<div class="small-2 columns">
		<span class="prefix">
			<i class="icon-search"></i>
		</span>
	</div>
	<div class="small-10 columns">
		<%= text_field_tag :equipment, nil, :class => 'equipsearch', :placeholder => 'Search equipment' %>
	</div>
</div>

app/views/shared/_tag_list.html.erb
<ul class="list tags">
	<% Tag.all.sort{|a,b| a.name <=> b.name}.each do |tag| %>
		<% link_text = '<li data-tag-id=' + tag.id.to_s + '><span class="right radius secondary label">' + tag.equipment.count.to_s + '</span><span class="name">' + tag.name + '</span></li>' %>
		<%= link_to link_text.html_safe, "#" %>
	<% end %>
</ul>